name: dart_import
description: A simple dart package to change all Dart/Flutter imports to relative format.
version: 0.0.1
author: Farzin Mirzaie<farzin.mirzaie@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
